#include "tttp_scancodes.h"
#include <stdlib.h>

const char* tttp_name_for_scancode(enum tttp_scancode code) {
  switch(code) {
  case KEY_BACKSPACE: return "Backspace";
  case KEY_TAB: return "Tab";
  case KEY_ENTER: return "Enter";
  case KEY_ESCAPE: return "Escape";
  case KEY_SPACE: return "Space";
  case KEY_EXCLAMATION_MARK: return "!";
  case KEY_DOUBLE_QUOTE: return "\"";
  case KEY_NUMBER_SIGN: return "#";
  case KEY_DOLLAR: return "$";
  case KEY_PERCENT: return "%";
  case KEY_AMPERSAND: return "&";
  case KEY_SINGLE_QUOTE: return "'";
  case KEY_LEFT_PARENTHESIS: return "(";
  case KEY_RIGHT_PARENTHESIS: return ")";
  case KEY_ASTERISK: return "*";
  case KEY_PLUS: return "+";
  case KEY_COMMA: return ",";
  case KEY_HYPHEN: return "-";
  case KEY_PERIOD: return ".";
  case KEY_SLASH: return "/";
  case KEY_0: return "0";
  case KEY_1: return "1";
  case KEY_2: return "2";
  case KEY_3: return "3";
  case KEY_4: return "4";
  case KEY_5: return "5";
  case KEY_6: return "6";
  case KEY_7: return "7";
  case KEY_8: return "8";
  case KEY_9: return "9";
  case KEY_COLON: return ":";
  case KEY_SEMICOLON: return ";";
  case KEY_LESS_THAN: return "<";
  case KEY_EQUAL: return "=";
  case KEY_GREATER_THAN: return ">";
  case KEY_QUESTION_MARK: return "?";
  case KEY_AT: return "@";
  case KEY_A: return "A";
  case KEY_B: return "B";
  case KEY_C: return "C";
  case KEY_D: return "D";
  case KEY_E: return "E";
  case KEY_F: return "F";
  case KEY_G: return "G";
  case KEY_H: return "H";
  case KEY_I: return "I";
  case KEY_J: return "J";
  case KEY_K: return "K";
  case KEY_L: return "L";
  case KEY_M: return "M";
  case KEY_N: return "N";
  case KEY_O: return "O";
  case KEY_P: return "P";
  case KEY_Q: return "Q";
  case KEY_R: return "R";
  case KEY_S: return "S";
  case KEY_T: return "T";
  case KEY_U: return "U";
  case KEY_V: return "V";
  case KEY_W: return "W";
  case KEY_X: return "X";
  case KEY_Y: return "Y";
  case KEY_Z: return "Z";
  case KEY_LEFT_BRACKET: return "[";
  case KEY_BACKSLASH: return "\\";
  case KEY_RIGHT_BRACKET: return "]";
  case KEY_CARET: return "^";
  case KEY_UNDERSCORE: return "_";
  case KEY_GRAVE: return "`";
  case KEY_LEFT_CURLY_BRACE: return "{";
  case KEY_VERTICAL_LINE: return "|";
  case KEY_RIGHT_CURLY_BRACE: return "}";
  case KEY_TILDE: return "~";
  case KEY_DELETE: return "Delete";
  case KEY_A_SCAN: return "A (scan)";
  case KEY_B_SCAN: return "B (scan)";
  case KEY_C_SCAN: return "C (scan)";
  case KEY_D_SCAN: return "D (scan)";
  case KEY_E_SCAN: return "E (scan)";
  case KEY_F_SCAN: return "F (scan)";
  case KEY_G_SCAN: return "G (scan)";
  case KEY_H_SCAN: return "H (scan)";
  case KEY_I_SCAN: return "I (scan)";
  case KEY_J_SCAN: return "J (scan)";
  case KEY_K_SCAN: return "K (scan)";
  case KEY_L_SCAN: return "L (scan)";
  case KEY_M_SCAN: return "M (scan)";
  case KEY_N_SCAN: return "N (scan)";
  case KEY_O_SCAN: return "O (scan)";
  case KEY_P_SCAN: return "P (scan)";
  case KEY_Q_SCAN: return "Q (scan)";
  case KEY_R_SCAN: return "R (scan)";
  case KEY_S_SCAN: return "S (scan)";
  case KEY_T_SCAN: return "T (scan)";
  case KEY_U_SCAN: return "U (scan)";
  case KEY_V_SCAN: return "V (scan)";
  case KEY_W_SCAN: return "W (scan)";
  case KEY_X_SCAN: return "X (scan)";
  case KEY_Y_SCAN: return "Y (scan)";
  case KEY_Z_SCAN: return "Z (scan)";
  case KEY_1_SCAN: return "1 (scan)";
  case KEY_2_SCAN: return "2 (scan)";
  case KEY_3_SCAN: return "3 (scan)";
  case KEY_4_SCAN: return "4 (scan)";
  case KEY_5_SCAN: return "5 (scan)";
  case KEY_6_SCAN: return "6 (scan)";
  case KEY_7_SCAN: return "7 (scan)";
  case KEY_8_SCAN: return "8 (scan)";
  case KEY_9_SCAN: return "9 (scan)";
  case KEY_0_SCAN: return "0 (scan)";
  case KEY_ENTER_SCAN: return "Enter (scan)";
  case KEY_ESCAPE_SCAN: return "Escape (scan)";
  case KEY_BACKSPACE_SCAN: return "Backspace (scan)";
  case KEY_TAB_SCAN: return "Tab (scan)";
  case KEY_SPACE_SCAN: return "Space (scan)";
  case KEY_HYPHEN_SCAN: return "- (scan)";
  case KEY_EQUAL_SCAN: return "= (scan)";
  case KEY_LEFT_BRACKET_SCAN: return "[ (scan)";
  case KEY_RIGHT_BRACKET_SCAN: return "] (scan)";
  case KEY_BACKSLASH_SCAN: return "\\ (scan)";
  case KEY_NUMBER_SIGN_SCAN: return "# (scan)";
  case KEY_SEMICOLON_SCAN: return "; (scan)";
  case KEY_SINGLE_QUOTE_SCAN: return "' (scan)";
  case KEY_GRAVE_SCAN: return "` (scan)";
  case KEY_COMMA_SCAN: return ", (scan)";
  case KEY_PERIOD_SCAN: return ". (scan)";
  case KEY_SLASH_SCAN: return "/ (scan)";
  case KEY_F1: return "F1";
  case KEY_F2: return "F2";
  case KEY_F3: return "F3";
  case KEY_F4: return "F4";
  case KEY_F5: return "F5";
  case KEY_F6: return "F6";
  case KEY_F7: return "F7";
  case KEY_F8: return "F8";
  case KEY_F9: return "F9";
  case KEY_F10: return "F10";
  case KEY_F11: return "F11";
  case KEY_F12: return "F12";
  case KEY_PRINTSCREEN: return "PrintScreen";
  case KEY_PAUSE: return "Pause";
  case KEY_INSERT: return "Insert";
  case KEY_HOME: return "Home";
  case KEY_PAGE_UP: return "Page Up";
  case KEY_DELETE_SCAN: return "Delete (scan)";
  case KEY_END: return "End";
  case KEY_PAGE_DOWN: return "Page Down";
  case KEY_RIGHT: return "Right";
  case KEY_LEFT: return "Left";
  case KEY_DOWN: return "Down";
  case KEY_UP: return "Up";
  case KEY_KEYPAD_CLEAR: return "Keypad Clear";
  case KEY_KEYPAD_SLASH: return "Keypad /";
  case KEY_KEYPAD_ASTERISK: return "Keypad *";
  case KEY_KEYPAD_HYPHEN: return "Keypad -";
  case KEY_KEYPAD_PLUS: return "Keypad +";
  case KEY_KEYPAD_ENTER: return "Keypad Enter";
  case KEY_KEYPAD_1: return "Keypad 1 OR End";
  case KEY_KEYPAD_2: return "Keypad 2 OR Down";
  case KEY_KEYPAD_3: return "Keypad 3 OR Page Down";
  case KEY_KEYPAD_4: return "Keypad 4 OR Left";
  case KEY_KEYPAD_5: return "Keypad 5";
  case KEY_KEYPAD_6: return "Keypad 6 OR Right";
  case KEY_KEYPAD_7: return "Keypad 7 OR Home";
  case KEY_KEYPAD_8: return "Keypad 8 OR Up";
  case KEY_KEYPAD_9: return "Keypad 9 OR Page Up";
  case KEY_KEYPAD_0: return "Keypad 0 OR Insert";
  case KEY_KEYPAD_PERIOD: return "Keypad . OR Delete";
  case KEY_NONHYPHENUS_BACKSLASH: return "Non-US \\";
  case KEY_APPLICATION: return "Application";
  case KEY_KEYPAD_EQUAL: return "Keypad =";
  case KEY_F13: return "F13";
  case KEY_F14: return "F14";
  case KEY_F15: return "F15";
  case KEY_F16: return "F16";
  case KEY_F17: return "F17";
  case KEY_F18: return "F18";
  case KEY_F19: return "F19";
  case KEY_F20: return "F20";
  case KEY_F21: return "F21";
  case KEY_F22: return "F22";
  case KEY_F23: return "F23";
  case KEY_F24: return "F24";
  case KEY_EXECUTE: return "Execute";
  case KEY_HELP: return "Help";
  case KEY_MENU: return "Menu";
  case KEY_SELECT: return "Select";
  case KEY_STOP: return "Stop";
  case KEY_AGAIN: return "Again";
  case KEY_UNDO: return "Undo";
  case KEY_CUT: return "Cut";
  case KEY_COPY: return "Copy";
  case KEY_PASTE: return "Paste";
  case KEY_FIND: return "Find";
  case KEY_MUTE: return "Mute";
  case KEY_VOLUME_UP: return "Volume Up";
  case KEY_VOLUME_DOWN: return "Volume Down";
  case KEY_CAPS_LOCK: return "Caps Lock";
  case KEY_NUM_LOCK: return "Num Lock";
  case KEY_SCROLL_LOCK: return "Scroll Lock";
  case KEY_KEYPAD_COMMA: return "Keypad ,";
  case KEY_KEYPAD_EQUAL_SIGN: return "Keypad Equal Sign";
  case KEY_INTERNATIONAL1: return "International1";
  case KEY_INTERNATIONAL2: return "International2";
  case KEY_INTERNATIONAL3: return "International3";
  case KEY_INTERNATIONAL4: return "International4";
  case KEY_INTERNATIONAL5: return "International5";
  case KEY_INTERNATIONAL6: return "International6";
  case KEY_INTERNATIONAL7: return "International7";
  case KEY_INTERNATIONAL8: return "International8";
  case KEY_INTERNATIONAL9: return "International9";
  case KEY_LANGUAGE1: return "Language1";
  case KEY_LANGUAGE2: return "Language2";
  case KEY_LANGUAGE3: return "Language3";
  case KEY_LANGUAGE4: return "Language4";
  case KEY_LANGUAGE5: return "Language5";
  case KEY_LANGUAGE6: return "Language6";
  case KEY_LANGUAGE7: return "Language7";
  case KEY_LANGUAGE8: return "Language8";
  case KEY_LANGUAGE9: return "Language9";
  case KEY_ALT_ERASE: return "Alt Erase";
  case KEY_SYSREQ: return "SysReq";
  case KEY_CANCEL: return "Cancel";
  case KEY_CLEAR: return "Clear";
  case KEY_PRIOR: return "Prior";
  case KEY_RETURN: return "Return";
  case KEY_SEPARATOR: return "Separator";
  case KEY_OUT: return "Out";
  case KEY_OPER: return "Oper";
  case KEY_CLEAR_OR_AGAIN: return "Clear or Again";
  case KEY_CRSEL: return "CrSel OR Props";
  case KEY_EXSEL: return "ExSel";
  case KEY_KEYPAD_00: return "Keypad 00";
  case KEY_KEYPAD_000: return "Keypad 000";
  case KEY_THOUSANDS_SEPARATOR: return "Thousands Separator";
  case KEY_DECIMAL_SEPARATOR: return "Decimal Separator";
  case KEY_CURRENCY_UNIT: return "Currency Unit";
  case KEY_CURRENCY_SUBUNIT: return "Currency Subunit";
  case KEY_KEYPAD_LEFT_PARENTHESIS: return "Keypad (";
  case KEY_KEYPAD_RIGHT_PARENTHESIS: return "Keypad )";
  case KEY_KEYPAD_LEFT_CURLY_BRACE: return "Keypad {";
  case KEY_KEYPAD_RIGHT_CURLY_BRACE: return "Keypad }";
  case KEY_KEYPAD_TAB: return "Keypad Tab";
  case KEY_KEYPAD_BACKSPACE: return "Keypad Backspace";
  case KEY_KEYPAD_A: return "Keypad A";
  case KEY_KEYPAD_B: return "Keypad B";
  case KEY_KEYPAD_C: return "Keypad C";
  case KEY_KEYPAD_D: return "Keypad D";
  case KEY_KEYPAD_E: return "Keypad E";
  case KEY_KEYPAD_F: return "Keypad F";
  case KEY_KEYPAD_XOR: return "Keypad XOR";
  case KEY_KEYPAD_CARET: return "Keypad ^";
  case KEY_KEYPAD_PERCENT: return "Keypad %";
  case KEY_KEYPAD_LESS_THAN: return "Keypad <";
  case KEY_KEYPAD_GREATER_THAN: return "Keypad >";
  case KEY_KEYPAD_AMPERSAND: return "Keypad &";
  case KEY_KEYPAD_AMPERSANDAMPERSAND: return "Keypad &&";
  case KEY_KEYPAD_VERTICAL_LINE: return "Keypad |";
  case KEY_KEYPAD_VERTICAL_LINEVERTICAL_LINE: return "Keypad ||";
  case KEY_KEYPAD_COLON: return "Keypad :";
  case KEY_KEYPAD_NUMBER_SIGN: return "Keypad #";
  case KEY_KEYPAD_SPACE: return "Keypad Space";
  case KEY_KEYPAD_AT: return "Keypad @";
  case KEY_KEYPAD_EXCLAMATION_MARK: return "Keypad !";
  case KEY_KEYPAD_MEMORY_STORE: return "Keypad Memory Store";
  case KEY_KEYPAD_MEMORY_RECALL: return "Keypad Memory Recall";
  case KEY_KEYPAD_MEMORY_CLEAR: return "Keypad Memory Clear";
  case KEY_KEYPAD_MEMORY_ADD: return "Keypad Memory Add";
  case KEY_KEYPAD_MEMORY_SUBTRACT: return "Keypad Memory Subtract";
  case KEY_KEYPAD_MEMORY_MULTIPLY: return "Keypad Memory Multiply";
  case KEY_KEYPAD_MEMORY_DIVIDE: return "Keypad Memory Divide";
  case KEY_KEYPAD_PLUSSLASHHYPHEN: return "Keypad +/-";
  case KEY_KEYPAD_CLEAR_ALT: return "Keypad Clear (alt)";
  case KEY_KEYPAD_CLEAR_ENTRY: return "Keypad Clear Entry";
  case KEY_KEYPAD_BINARY: return "Keypad Binary";
  case KEY_KEYPAD_OCTAL: return "Keypad Octal";
  case KEY_KEYPAD_DECIMAL: return "Keypad Decimal";
  case KEY_KEYPAD_HEXADECIMAL: return "Keypad Hexadecimal";
  case KEY_LEFT_CONTROL: return "Left Control";
  case KEY_LEFT_SHIFT: return "Left Shift";
  case KEY_LEFT_ALT: return "Left Alt";
  case KEY_LEFT_GUI: return "Left GUI";
  case KEY_RIGHT_CONTROL: return "Right Control";
  case KEY_RIGHT_SHIFT: return "Right Shift";
  case KEY_RIGHT_ALT: return "Right Alt";
  case KEY_RIGHT_GUI: return "Right GUI";
  default: return NULL;
  }
}

const char* tttp_identifier_for_scancode(enum tttp_scancode code) {
  switch(code) {
  case KEY_BACKSPACE: return "KEY_BACKSPACE";
  case KEY_TAB: return "KEY_TAB";
  case KEY_ENTER: return "KEY_ENTER";
  case KEY_ESCAPE: return "KEY_ESCAPE";
  case KEY_SPACE: return "KEY_SPACE";
  case KEY_EXCLAMATION_MARK: return "KEY_EXCLAMATION_MARK";
  case KEY_DOUBLE_QUOTE: return "KEY_DOUBLE_QUOTE";
  case KEY_NUMBER_SIGN: return "KEY_NUMBER_SIGN";
  case KEY_DOLLAR: return "KEY_DOLLAR";
  case KEY_PERCENT: return "KEY_PERCENT";
  case KEY_AMPERSAND: return "KEY_AMPERSAND";
  case KEY_SINGLE_QUOTE: return "KEY_SINGLE_QUOTE";
  case KEY_LEFT_PARENTHESIS: return "KEY_LEFT_PARENTHESIS";
  case KEY_RIGHT_PARENTHESIS: return "KEY_RIGHT_PARENTHESIS";
  case KEY_ASTERISK: return "KEY_ASTERISK";
  case KEY_PLUS: return "KEY_PLUS";
  case KEY_COMMA: return "KEY_COMMA";
  case KEY_HYPHEN: return "KEY_HYPHEN";
  case KEY_PERIOD: return "KEY_PERIOD";
  case KEY_SLASH: return "KEY_SLASH";
  case KEY_0: return "KEY_0";
  case KEY_1: return "KEY_1";
  case KEY_2: return "KEY_2";
  case KEY_3: return "KEY_3";
  case KEY_4: return "KEY_4";
  case KEY_5: return "KEY_5";
  case KEY_6: return "KEY_6";
  case KEY_7: return "KEY_7";
  case KEY_8: return "KEY_8";
  case KEY_9: return "KEY_9";
  case KEY_COLON: return "KEY_COLON";
  case KEY_SEMICOLON: return "KEY_SEMICOLON";
  case KEY_LESS_THAN: return "KEY_LESS_THAN";
  case KEY_EQUAL: return "KEY_EQUAL";
  case KEY_GREATER_THAN: return "KEY_GREATER_THAN";
  case KEY_QUESTION_MARK: return "KEY_QUESTION_MARK";
  case KEY_AT: return "KEY_AT";
  case KEY_A: return "KEY_A";
  case KEY_B: return "KEY_B";
  case KEY_C: return "KEY_C";
  case KEY_D: return "KEY_D";
  case KEY_E: return "KEY_E";
  case KEY_F: return "KEY_F";
  case KEY_G: return "KEY_G";
  case KEY_H: return "KEY_H";
  case KEY_I: return "KEY_I";
  case KEY_J: return "KEY_J";
  case KEY_K: return "KEY_K";
  case KEY_L: return "KEY_L";
  case KEY_M: return "KEY_M";
  case KEY_N: return "KEY_N";
  case KEY_O: return "KEY_O";
  case KEY_P: return "KEY_P";
  case KEY_Q: return "KEY_Q";
  case KEY_R: return "KEY_R";
  case KEY_S: return "KEY_S";
  case KEY_T: return "KEY_T";
  case KEY_U: return "KEY_U";
  case KEY_V: return "KEY_V";
  case KEY_W: return "KEY_W";
  case KEY_X: return "KEY_X";
  case KEY_Y: return "KEY_Y";
  case KEY_Z: return "KEY_Z";
  case KEY_LEFT_BRACKET: return "KEY_LEFT_BRACKET";
  case KEY_BACKSLASH: return "KEY_BACKSLASH";
  case KEY_RIGHT_BRACKET: return "KEY_RIGHT_BRACKET";
  case KEY_CARET: return "KEY_CARET";
  case KEY_UNDERSCORE: return "KEY_UNDERSCORE";
  case KEY_GRAVE: return "KEY_GRAVE";
  case KEY_LEFT_CURLY_BRACE: return "KEY_LEFT_CURLY_BRACE";
  case KEY_VERTICAL_LINE: return "KEY_VERTICAL_LINE";
  case KEY_RIGHT_CURLY_BRACE: return "KEY_RIGHT_CURLY_BRACE";
  case KEY_TILDE: return "KEY_TILDE";
  case KEY_DELETE: return "KEY_DELETE";
  case KEY_A_SCAN: return "KEY_A_SCAN";
  case KEY_B_SCAN: return "KEY_B_SCAN";
  case KEY_C_SCAN: return "KEY_C_SCAN";
  case KEY_D_SCAN: return "KEY_D_SCAN";
  case KEY_E_SCAN: return "KEY_E_SCAN";
  case KEY_F_SCAN: return "KEY_F_SCAN";
  case KEY_G_SCAN: return "KEY_G_SCAN";
  case KEY_H_SCAN: return "KEY_H_SCAN";
  case KEY_I_SCAN: return "KEY_I_SCAN";
  case KEY_J_SCAN: return "KEY_J_SCAN";
  case KEY_K_SCAN: return "KEY_K_SCAN";
  case KEY_L_SCAN: return "KEY_L_SCAN";
  case KEY_M_SCAN: return "KEY_M_SCAN";
  case KEY_N_SCAN: return "KEY_N_SCAN";
  case KEY_O_SCAN: return "KEY_O_SCAN";
  case KEY_P_SCAN: return "KEY_P_SCAN";
  case KEY_Q_SCAN: return "KEY_Q_SCAN";
  case KEY_R_SCAN: return "KEY_R_SCAN";
  case KEY_S_SCAN: return "KEY_S_SCAN";
  case KEY_T_SCAN: return "KEY_T_SCAN";
  case KEY_U_SCAN: return "KEY_U_SCAN";
  case KEY_V_SCAN: return "KEY_V_SCAN";
  case KEY_W_SCAN: return "KEY_W_SCAN";
  case KEY_X_SCAN: return "KEY_X_SCAN";
  case KEY_Y_SCAN: return "KEY_Y_SCAN";
  case KEY_Z_SCAN: return "KEY_Z_SCAN";
  case KEY_1_SCAN: return "KEY_1_SCAN";
  case KEY_2_SCAN: return "KEY_2_SCAN";
  case KEY_3_SCAN: return "KEY_3_SCAN";
  case KEY_4_SCAN: return "KEY_4_SCAN";
  case KEY_5_SCAN: return "KEY_5_SCAN";
  case KEY_6_SCAN: return "KEY_6_SCAN";
  case KEY_7_SCAN: return "KEY_7_SCAN";
  case KEY_8_SCAN: return "KEY_8_SCAN";
  case KEY_9_SCAN: return "KEY_9_SCAN";
  case KEY_0_SCAN: return "KEY_0_SCAN";
  case KEY_ENTER_SCAN: return "KEY_ENTER_SCAN";
  case KEY_ESCAPE_SCAN: return "KEY_ESCAPE_SCAN";
  case KEY_BACKSPACE_SCAN: return "KEY_BACKSPACE_SCAN";
  case KEY_TAB_SCAN: return "KEY_TAB_SCAN";
  case KEY_SPACE_SCAN: return "KEY_SPACE_SCAN";
  case KEY_HYPHEN_SCAN: return "KEY_HYPHEN_SCAN";
  case KEY_EQUAL_SCAN: return "KEY_EQUAL_SCAN";
  case KEY_LEFT_BRACKET_SCAN: return "KEY_LEFT_BRACKET_SCAN";
  case KEY_RIGHT_BRACKET_SCAN: return "KEY_RIGHT_BRACKET_SCAN";
  case KEY_BACKSLASH_SCAN: return "KEY_BACKSLASH_SCAN";
  case KEY_NUMBER_SIGN_SCAN: return "KEY_NUMBER_SIGN_SCAN";
  case KEY_SEMICOLON_SCAN: return "KEY_SEMICOLON_SCAN";
  case KEY_SINGLE_QUOTE_SCAN: return "KEY_SINGLE_QUOTE_SCAN";
  case KEY_GRAVE_SCAN: return "KEY_GRAVE_SCAN";
  case KEY_COMMA_SCAN: return "KEY_COMMA_SCAN";
  case KEY_PERIOD_SCAN: return "KEY_PERIOD_SCAN";
  case KEY_SLASH_SCAN: return "KEY_SLASH_SCAN";
  case KEY_F1: return "KEY_F1";
  case KEY_F2: return "KEY_F2";
  case KEY_F3: return "KEY_F3";
  case KEY_F4: return "KEY_F4";
  case KEY_F5: return "KEY_F5";
  case KEY_F6: return "KEY_F6";
  case KEY_F7: return "KEY_F7";
  case KEY_F8: return "KEY_F8";
  case KEY_F9: return "KEY_F9";
  case KEY_F10: return "KEY_F10";
  case KEY_F11: return "KEY_F11";
  case KEY_F12: return "KEY_F12";
  case KEY_PRINTSCREEN: return "KEY_PRINTSCREEN";
  case KEY_PAUSE: return "KEY_PAUSE";
  case KEY_INSERT: return "KEY_INSERT";
  case KEY_HOME: return "KEY_HOME";
  case KEY_PAGE_UP: return "KEY_PAGE_UP";
  case KEY_DELETE_SCAN: return "KEY_DELETE_SCAN";
  case KEY_END: return "KEY_END";
  case KEY_PAGE_DOWN: return "KEY_PAGE_DOWN";
  case KEY_RIGHT: return "KEY_RIGHT";
  case KEY_LEFT: return "KEY_LEFT";
  case KEY_DOWN: return "KEY_DOWN";
  case KEY_UP: return "KEY_UP";
  case KEY_KEYPAD_CLEAR: return "KEY_KEYPAD_CLEAR";
  case KEY_KEYPAD_SLASH: return "KEY_KEYPAD_SLASH";
  case KEY_KEYPAD_ASTERISK: return "KEY_KEYPAD_ASTERISK";
  case KEY_KEYPAD_HYPHEN: return "KEY_KEYPAD_HYPHEN";
  case KEY_KEYPAD_PLUS: return "KEY_KEYPAD_PLUS";
  case KEY_KEYPAD_ENTER: return "KEY_KEYPAD_ENTER";
  case KEY_KEYPAD_1: return "KEY_KEYPAD_1";
  case KEY_KEYPAD_2: return "KEY_KEYPAD_2";
  case KEY_KEYPAD_3: return "KEY_KEYPAD_3";
  case KEY_KEYPAD_4: return "KEY_KEYPAD_4";
  case KEY_KEYPAD_5: return "KEY_KEYPAD_5";
  case KEY_KEYPAD_6: return "KEY_KEYPAD_6";
  case KEY_KEYPAD_7: return "KEY_KEYPAD_7";
  case KEY_KEYPAD_8: return "KEY_KEYPAD_8";
  case KEY_KEYPAD_9: return "KEY_KEYPAD_9";
  case KEY_KEYPAD_0: return "KEY_KEYPAD_0";
  case KEY_KEYPAD_PERIOD: return "KEY_KEYPAD_PERIOD";
  case KEY_NONHYPHENUS_BACKSLASH: return "KEY_NONHYPHENUS_BACKSLASH";
  case KEY_APPLICATION: return "KEY_APPLICATION";
  case KEY_KEYPAD_EQUAL: return "KEY_KEYPAD_EQUAL";
  case KEY_F13: return "KEY_F13";
  case KEY_F14: return "KEY_F14";
  case KEY_F15: return "KEY_F15";
  case KEY_F16: return "KEY_F16";
  case KEY_F17: return "KEY_F17";
  case KEY_F18: return "KEY_F18";
  case KEY_F19: return "KEY_F19";
  case KEY_F20: return "KEY_F20";
  case KEY_F21: return "KEY_F21";
  case KEY_F22: return "KEY_F22";
  case KEY_F23: return "KEY_F23";
  case KEY_F24: return "KEY_F24";
  case KEY_EXECUTE: return "KEY_EXECUTE";
  case KEY_HELP: return "KEY_HELP";
  case KEY_MENU: return "KEY_MENU";
  case KEY_SELECT: return "KEY_SELECT";
  case KEY_STOP: return "KEY_STOP";
  case KEY_AGAIN: return "KEY_AGAIN";
  case KEY_UNDO: return "KEY_UNDO";
  case KEY_CUT: return "KEY_CUT";
  case KEY_COPY: return "KEY_COPY";
  case KEY_PASTE: return "KEY_PASTE";
  case KEY_FIND: return "KEY_FIND";
  case KEY_MUTE: return "KEY_MUTE";
  case KEY_VOLUME_UP: return "KEY_VOLUME_UP";
  case KEY_VOLUME_DOWN: return "KEY_VOLUME_DOWN";
  case KEY_CAPS_LOCK: return "KEY_CAPS_LOCK";
  case KEY_NUM_LOCK: return "KEY_NUM_LOCK";
  case KEY_SCROLL_LOCK: return "KEY_SCROLL_LOCK";
  case KEY_KEYPAD_COMMA: return "KEY_KEYPAD_COMMA";
  case KEY_KEYPAD_EQUAL_SIGN: return "KEY_KEYPAD_EQUAL_SIGN";
  case KEY_INTERNATIONAL1: return "KEY_INTERNATIONAL1";
  case KEY_INTERNATIONAL2: return "KEY_INTERNATIONAL2";
  case KEY_INTERNATIONAL3: return "KEY_INTERNATIONAL3";
  case KEY_INTERNATIONAL4: return "KEY_INTERNATIONAL4";
  case KEY_INTERNATIONAL5: return "KEY_INTERNATIONAL5";
  case KEY_INTERNATIONAL6: return "KEY_INTERNATIONAL6";
  case KEY_INTERNATIONAL7: return "KEY_INTERNATIONAL7";
  case KEY_INTERNATIONAL8: return "KEY_INTERNATIONAL8";
  case KEY_INTERNATIONAL9: return "KEY_INTERNATIONAL9";
  case KEY_LANGUAGE1: return "KEY_LANGUAGE1";
  case KEY_LANGUAGE2: return "KEY_LANGUAGE2";
  case KEY_LANGUAGE3: return "KEY_LANGUAGE3";
  case KEY_LANGUAGE4: return "KEY_LANGUAGE4";
  case KEY_LANGUAGE5: return "KEY_LANGUAGE5";
  case KEY_LANGUAGE6: return "KEY_LANGUAGE6";
  case KEY_LANGUAGE7: return "KEY_LANGUAGE7";
  case KEY_LANGUAGE8: return "KEY_LANGUAGE8";
  case KEY_LANGUAGE9: return "KEY_LANGUAGE9";
  case KEY_ALT_ERASE: return "KEY_ALT_ERASE";
  case KEY_SYSREQ: return "KEY_SYSREQ";
  case KEY_CANCEL: return "KEY_CANCEL";
  case KEY_CLEAR: return "KEY_CLEAR";
  case KEY_PRIOR: return "KEY_PRIOR";
  case KEY_RETURN: return "KEY_RETURN";
  case KEY_SEPARATOR: return "KEY_SEPARATOR";
  case KEY_OUT: return "KEY_OUT";
  case KEY_OPER: return "KEY_OPER";
  case KEY_CLEAR_OR_AGAIN: return "KEY_CLEAR_OR_AGAIN";
  case KEY_CRSEL: return "KEY_CRSEL";
  case KEY_EXSEL: return "KEY_EXSEL";
  case KEY_KEYPAD_00: return "KEY_KEYPAD_00";
  case KEY_KEYPAD_000: return "KEY_KEYPAD_000";
  case KEY_THOUSANDS_SEPARATOR: return "KEY_THOUSANDS_SEPARATOR";
  case KEY_DECIMAL_SEPARATOR: return "KEY_DECIMAL_SEPARATOR";
  case KEY_CURRENCY_UNIT: return "KEY_CURRENCY_UNIT";
  case KEY_CURRENCY_SUBUNIT: return "KEY_CURRENCY_SUBUNIT";
  case KEY_KEYPAD_LEFT_PARENTHESIS: return "KEY_KEYPAD_LEFT_PARENTHESIS";
  case KEY_KEYPAD_RIGHT_PARENTHESIS: return "KEY_KEYPAD_RIGHT_PARENTHESIS";
  case KEY_KEYPAD_LEFT_CURLY_BRACE: return "KEY_KEYPAD_LEFT_CURLY_BRACE";
  case KEY_KEYPAD_RIGHT_CURLY_BRACE: return "KEY_KEYPAD_RIGHT_CURLY_BRACE";
  case KEY_KEYPAD_TAB: return "KEY_KEYPAD_TAB";
  case KEY_KEYPAD_BACKSPACE: return "KEY_KEYPAD_BACKSPACE";
  case KEY_KEYPAD_A: return "KEY_KEYPAD_A";
  case KEY_KEYPAD_B: return "KEY_KEYPAD_B";
  case KEY_KEYPAD_C: return "KEY_KEYPAD_C";
  case KEY_KEYPAD_D: return "KEY_KEYPAD_D";
  case KEY_KEYPAD_E: return "KEY_KEYPAD_E";
  case KEY_KEYPAD_F: return "KEY_KEYPAD_F";
  case KEY_KEYPAD_XOR: return "KEY_KEYPAD_XOR";
  case KEY_KEYPAD_CARET: return "KEY_KEYPAD_CARET";
  case KEY_KEYPAD_PERCENT: return "KEY_KEYPAD_PERCENT";
  case KEY_KEYPAD_LESS_THAN: return "KEY_KEYPAD_LESS_THAN";
  case KEY_KEYPAD_GREATER_THAN: return "KEY_KEYPAD_GREATER_THAN";
  case KEY_KEYPAD_AMPERSAND: return "KEY_KEYPAD_AMPERSAND";
  case KEY_KEYPAD_AMPERSANDAMPERSAND: return "KEY_KEYPAD_AMPERSANDAMPERSAND";
  case KEY_KEYPAD_VERTICAL_LINE: return "KEY_KEYPAD_VERTICAL_LINE";
  case KEY_KEYPAD_VERTICAL_LINEVERTICAL_LINE: return "KEY_KEYPAD_VERTICAL_LINEVERTICAL_LINE";
  case KEY_KEYPAD_COLON: return "KEY_KEYPAD_COLON";
  case KEY_KEYPAD_NUMBER_SIGN: return "KEY_KEYPAD_NUMBER_SIGN";
  case KEY_KEYPAD_SPACE: return "KEY_KEYPAD_SPACE";
  case KEY_KEYPAD_AT: return "KEY_KEYPAD_AT";
  case KEY_KEYPAD_EXCLAMATION_MARK: return "KEY_KEYPAD_EXCLAMATION_MARK";
  case KEY_KEYPAD_MEMORY_STORE: return "KEY_KEYPAD_MEMORY_STORE";
  case KEY_KEYPAD_MEMORY_RECALL: return "KEY_KEYPAD_MEMORY_RECALL";
  case KEY_KEYPAD_MEMORY_CLEAR: return "KEY_KEYPAD_MEMORY_CLEAR";
  case KEY_KEYPAD_MEMORY_ADD: return "KEY_KEYPAD_MEMORY_ADD";
  case KEY_KEYPAD_MEMORY_SUBTRACT: return "KEY_KEYPAD_MEMORY_SUBTRACT";
  case KEY_KEYPAD_MEMORY_MULTIPLY: return "KEY_KEYPAD_MEMORY_MULTIPLY";
  case KEY_KEYPAD_MEMORY_DIVIDE: return "KEY_KEYPAD_MEMORY_DIVIDE";
  case KEY_KEYPAD_PLUSSLASHHYPHEN: return "KEY_KEYPAD_PLUSSLASHHYPHEN";
  case KEY_KEYPAD_CLEAR_ALT: return "KEY_KEYPAD_CLEAR_ALT";
  case KEY_KEYPAD_CLEAR_ENTRY: return "KEY_KEYPAD_CLEAR_ENTRY";
  case KEY_KEYPAD_BINARY: return "KEY_KEYPAD_BINARY";
  case KEY_KEYPAD_OCTAL: return "KEY_KEYPAD_OCTAL";
  case KEY_KEYPAD_DECIMAL: return "KEY_KEYPAD_DECIMAL";
  case KEY_KEYPAD_HEXADECIMAL: return "KEY_KEYPAD_HEXADECIMAL";
  case KEY_LEFT_CONTROL: return "KEY_LEFT_CONTROL";
  case KEY_LEFT_SHIFT: return "KEY_LEFT_SHIFT";
  case KEY_LEFT_ALT: return "KEY_LEFT_ALT";
  case KEY_LEFT_GUI: return "KEY_LEFT_GUI";
  case KEY_RIGHT_CONTROL: return "KEY_RIGHT_CONTROL";
  case KEY_RIGHT_SHIFT: return "KEY_RIGHT_SHIFT";
  case KEY_RIGHT_ALT: return "KEY_RIGHT_ALT";
  case KEY_RIGHT_GUI: return "KEY_RIGHT_GUI";
  default: return NULL;
  }
}
